openapi: 3.0.0
info:
  title: Leaderboards Admin API
  version: '1.0'
  description:  |
    # Introduction

    This is the API specification for the Unity Leaderboards Admin service that enables
    game developers to create and edit leaderboard configurations for their games.

    # General Information

    A leaderboard configuration can be created and edited through this API. In addition, player scores
    can be retrieved (either as a set of leaderboard entries or for a particular player) and deleted, and
    leaderboards may be reset, optionally retaining a read-only version of the scores stored in the leaderboard
    at the time of the reset.

    ## Rate Limits

    The API has rate limiting in place. Request are limited to 10 requests per second, and 1000 requests per 30 minute period.

    The API responds with a `429` HTTP status code if the rate limit is
    exceeded.

    It will also respond with a `Retry-After` header to be used in conjunction with a client's retry logic.
    The value is the number of seconds until a request for the given player will be accepted.     

tags:
  - name: Leaderboards
    description: Associated with the Leaderboards service

servers:
  - url: 'https://services.api.unity.com'

paths:
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards':
    post:
      summary: Create Leaderboard
      operationId: createLeaderboard
      tags:
        - Leaderboards
      description: Add leaderboard to project environment
      security:
        - ServiceAccount: ['live_ops.leaderboards.configurations.create']
    get:
      summary: Get Leaderboard Configs
      operationId: getLeaderboardConfigs
      tags:
        - Leaderboards
      description: List leaderboard configurations for the given project environment
      security:
        - ServiceAccount: ['live_ops.leaderboards.configurations.list']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}':
    get:
      summary: Get Leaderboard Config
      tags:
        - Leaderboards
      operationId: getLeaderboardConfig
      description: 'Retrieves the configuration for a specific leaderboard'
      security:
        - ServiceAccount: ['live_ops.leaderboards.configurations.get']
    patch:
      summary: Update Leaderboard Config
      tags:
        - Leaderboards
      operationId: updateLeaderboardConfig
      description: 'Updates the configuration for a specific leaderboard'
      security:
        - ServiceAccount: ['live_ops.leaderboards.configurations.update']
    delete:
      summary: Delete Leaderboard
      tags:
        - Leaderboards
      operationId: deleteLeaderboard
      description: 'Deletes the configuration and scores for a specific leaderboard'
      security:
        - ServiceAccount: ['live_ops.leaderboards.configurations.delete']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/buckets':
    get:
      summary: Get Bucket IDs
      tags:
        - Leaderboards
      operationId: getLeaderboardBuckets
      description: 'Retrieves the bucket IDs for a specific bucketed leaderboard'
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.list']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/scores':
    get:
      summary: Get Scores
      tags:
        - Leaderboards
      operationId: getLeaderboardScores
      description: |-
        Get list of scores and ranks for the specified leaderboard, with specified pagination.
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.list']
    delete:
      summary: Reset Scores
      tags:
        - Leaderboards
      operationId: resetLeaderboardScores
      description: |-
        Reset the scores for the specified leaderboard, optionally archiving the existing scores before resetting. When archiving, the operation will return the version ID of the archive version that has been created. Each leaderboard can have up to 10,000 archives. Beyond this limit, the system will automatically delete the oldest archives on a first-in, first-out (FIFO) basis.
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.delete']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/tiers/{tierId}/scores':
    get:
      summary: Get Scores By Tier
      tags:
        - Leaderboards
      operationId: getLeaderboardScoresByTier
      description: |-
        Get list of scores and ranks for the specified leaderboard, within the specified tier, with specified pagination.
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.list']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/buckets/{bucketId}/scores':
    get:
      summary: Get Bucket Scores
      tags:
        - Leaderboards
      operationId: getLeaderboardBucketScores
      description: |-
        Get list of scores and ranks for the specified bucket from the specified leaderboard, with specified pagination.
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.list']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/buckets/{bucketId}/tiers/{tierId}/scores':
    get:
      summary: Get Bucket Scores By Tier
      tags:
        - Leaderboards
      operationId: getLeaderboardBucketScoresByTier
      description: |-
        Get list of scores and ranks for the specified bucket from the specified leaderboard, within the specified tier, with specified pagination.
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.list']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/scores/players':
    post:
      summary: Get Scores By PlayerIds
      tags:
        - Leaderboards
      operationId: getLeaderboardScoresByPlayerIds
      description: |-
        Get list of scores and ranks for the specified leaderboard, with specified playerIds.
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/versions/{versionId}/scores/players':
    post:
      summary: Get Scores By PlayerIds for Archived Leaderboard
      tags:
        - Leaderboards
      operationId: getLeaderboardScoresByPlayerIdsArchiveVersion
      description: |-
        Get list of scores and ranks for an archived leaderboard, with specified playerIds.
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/scores/players/{playerId}/range':
    get:
      summary: Get Player Range
      tags:
        - Leaderboards
      operationId: getLeaderboardScoresPlayerRange
      description: |-
        Get the list of neighbouring players for the specified player Id.
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/versions/{versionId}/scores/players/{playerId}/range':
    get:
      summary: Get Player Range for Archived Leaderboard
      tags:
        - Leaderboards
      operationId: getLeaderboardVersionScoresPlayerRange
      description: |-
        Get the list of neighbouring players for the specified player Id for an archived leaderboard.
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/scores/players/{playerId}':
    get:
      summary: Get Player Score
      tags:
        - Leaderboards
      operationId: getLeaderboardPlayerScore
      description: |-
        Get score and rank for the specified player in the specified leaderboard.
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.get']
    delete:
      summary: Delete Player Score
      tags:
        - Leaderboards
      operationId: deleteLeaderboardPlayerScore
      description: 'Deletes the score for a specific player from a specific leaderboard'
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.delete']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/scores/players/{playerId}/purge':
    delete:
      summary: Delete Player Score From All Live Leaderboards
      tags:
        - Leaderboards
      operationId: deleteLeaderboardPlayerScoreAllLiveLeaderboards
      description: 'Deletes the score for a specific player from all live leaderboards'
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.delete']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/versions/{versionId}/scores':
    get:
      summary: Get Version Scores
      tags:
        - Leaderboards
      operationId: getLeaderboardVersionScores
      description: |-
        Get list of scores and ranks for the specified archived leaderboard version, with specified pagination.
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.list']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/versions/{versionId}/tiers/{tierId}/scores':
    get:
      summary: Get Version Scores By Tier
      tags:
        - Leaderboards
      operationId: getLeaderboardVersionScoresByTier
      description: |-
        Get list of scores and ranks for the specified archived leaderboard version, within the specified tier, with specified pagination.
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.list']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/versions/{versionId}/buckets':
    get:
      summary: Get Version Bucket IDs
      tags:
        - Leaderboards
      operationId: getLeaderboardVersionBuckets
      description: |-
        Get the bucket IDs for a specific bucketed leaderboard archive version, with specified pagination.
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.list']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/versions/{versionId}/buckets/{bucketId}/scores':
    get:
      summary: Get Version Bucket Scores
      tags:
        - Leaderboards
      operationId: getLeaderboardVersionBucketScores
      description: |-
        Get list of scores and ranks for the specified bucket from the specified leaderboard version, with specified pagination.
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.list']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/versions/{versionId}/buckets/{bucketId}/tiers/{tierId}/scores':
    get:
      summary: Get Version Bucket Scores By Tier
      tags:
        - Leaderboards
      operationId: getLeaderboardVersionBucketScoresByTier
      description: |-
        Get list of scores and ranks for the specified bucket from the specified leaderboard version, within the specified tier, with specified pagination.
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.list']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/versions/{versionId}/scores/players/{playerId}':
    get:
      summary: Get Version Player Score
      tags:
        - Leaderboards
      operationId: getLeaderboardVersionPlayerScore
      description: |-
        Get score and rank for the specified player in the specified archived leaderboard version.
      security:
        - ServiceAccount: ['live_ops.leaderboards.scores.get']
  '/leaderboards/v1/projects/{projectId}/environments/{environmentId}/leaderboards/{leaderboardId}/versions/{versionId}':
    delete:
      summary: Delete Leaderboard Version
      tags:
        - Leaderboards
      operationId: deleteLeaderboardVersion
      description: |-
        Delete the specified leaderboard version.
components:
  securitySchemes:
    ServiceAccount: 
      type: http
      scheme: basic
      description: |-
        To get started with Authentication, please visit the [Service Account Authentication section](https://services.docs.unity.com/docs/service-account-auth).


        For this API, you will need to add the following role(s) to your service account :
        | Role Type | Role Name | Permissions |
        | --- | --- | --- |
        | Project Level Role | Leaderboards Admin | <ul><li>live_ops.leaderboards.configurations.get</li><li>live_ops.leaderboards.configurations.list</li><li>live_ops.leaderboards.configurations.create</li><li>live_ops.leaderboards.configurations.update</li><li>live_ops.leaderboards.configurations.delete</li><li>live_ops.leaderboards.scores.get</li><li>live_ops.leaderboards.scores.list</li><li>live_ops.leaderboards.scores.delete</li></ul> |
        | Project Level Role | Leaderboards Viewer | <ul><li>live_ops.leaderboards.configurations.get</li><li>live_ops.leaderboards.configurations.list</li><li>live_ops.leaderboards.scores.get</li><li>live_ops.leaderboards.scores.list</li></ul> |